spring.datasource.url=jdbc:mysql://localhost:3306/quantity_measurement?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=7088323289Digambar@123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Connection Pool
spring.datasource.hikari.maximum-pool-size=10

# JWT Configuration
jwt.secret=dGhpc0lzQVN1cGVyU2VjcmV0S2V5Rm9ySldUVG9rZW5HZW5lcmF0aW9uMjAyNA==
jwt.expiration=86400000

# Swagger
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# Google OAuth2 - Replace with your Google Cloud Console Client ID
google.client-id=127502197321-asmrb0h36b23sb0dac5t3gempn5t8p2e.apps.googleusercontent.com